"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['draft3.py']
DATA_FILES = ['PFA-POS Alignment Traveler-11563768dd12.json', 'backdrop.jpg','logo.jpg']
OPTIONS = {'iconfile': 'logo.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
